# Generated by Django 5.2 on 2025-04-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='new_email',
            field=models.EmailField(default='default@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
