# Generated by Django 5.2 on 2025-04-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_submission_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
