# Generated by Django 5.2 on 2025-04-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_title_postattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('announcement', 'Announcement'), ('classwork', 'Classwork')], default='post', max_length=20),
        ),
    ]
