# Generated by Django 5.2 on 2025-04-28 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_due_date_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroommember',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.classroom'),
        ),
    ]
