# Generated by Django 5.2 on 2025-04-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_classroommember_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
