# Generated by Django 5.2 on 2025-04-29 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_note_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notefile',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.note'),
        ),
        migrations.CreateModel(
            name='BoughtFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.notefile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
