# Generated by Django 5.2 on 2025-04-30 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_notefile_note_boughtfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.classroom'),
        ),
    ]
